const products = [
    {
        _id: '1',
        name: 'Organic Avocado',
        images: ['/images/avocados/1.jpg', '/images/avocados/2.jpg', '/images/avocados/3.jpg', '/images/avocados/4.jpg'],
        origin: 'Lam Dong',
        decription: 'Grown in Love Valley, Lam Dong, Vietnam, our avocado is beloved for its mild taste and rich texture. We carefully pick, package and deliver to your kitchen.',
        seller: 'Love Valley Farm',
        category: 'Fruit',
        unitPrice: 5.69,
        discount: 0.1,
        uom: 'kg',
        package: 5,
        countInStock: 450,
        rating: 4.8,
        numReviews: 50,
        shippingArea: 'Nationwide',
    },
    {
        _id: '2',
        name: 'Global Gap Custard Apple',
        images: ['/images/custard-apples/1.jpg', '/images/custard-apples/2.jpg'],
        origin: 'Tay Ninh',
        decription: 'Our famous custard apples are grown in the area of Ba Den Hill  ',
        seller: 'Sun Farm',
        category: 'Fruit',
        unitPrice: 6.19,
        discount: 0.15,
        uom: 'kg',
        package: 10,
        countInStock: 500,
        rating: 4.5,
        numReviews: 20,
        shippingArea: 'Nationwide',
    },
    {
        _id: '3',
        name: 'Global Gap Custard Apple',
        images: ['/images/mangos/1.jpg', '/images/mangos/2.jpg', '/images/mangos/3.jpg', '/images/mangos/4.jpg'],
        origin: 'Tien Giang',
        decription: 'Each mano weighs around 1kg. Our manges feature refreshing and sweet taste and pleasant aroma. Our farm is certified with Global Gap standards.',
        seller: 'River Farm',
        category: 'Fruit',
        unitPrice: 4.29,
        discount: 0.09,
        uom: 'kg',
        package: 10,
        countInStock: 300,
        rating: 4.8,
        numReviews: 25,
        shippingArea: 'Nationwide',
    },
    {
        _id: '4',
        name: 'Green Orange',
        images: ['/images/oranges/1.jpg', '/images/oranges/2.jpg', '/images/oranges/3.jpg', '/images/oranges/4.jpg'],
        origin: 'Cu Chi, Ho Chi Minh City',
        decription: 'We plant happy oranges and carefully pick and deliver to your home. Our green oranges are perfect for juice and smoothies.',
        seller: 'Happy Farmers',
        category: 'Fruit',
        unitPrice: 3.29,
        discount: 0.05,
        uom: 'kg',
        package: 10,
        countInStock: 600,
        rating: 4.5,
        numReviews: 28,
        shippingArea: 'Ho Chi Minh city'
    },
    {
        _id: '5',
        name: 'VietGap Red Seed Water Melon',
        images: ['/images/watermelons/1.jpg', '/images/watermelons/2.jpg'],
        origin: 'Tien Giang',
        decription: 'Our sweet yet mild red water melons are perfect for summer parties, picnics. We only pick the best ones and carefully pack.',
        seller: 'River Farm',
        category: 'Fruit',
        unitPrice: 3.29,
        discount: 0.11,
        uom: 'kg',
        package: 10,
        countInStock: 600,
        rating: 4.5,
        numReviews: 23,
        shippingArea: 'Ho Chi Minh city'
    },
];

export default products;
